services:
  demo-1:
    container_name: demo-1
    image: nginx:latest
    ports:
      - 8080:80
    networks:
      - frontend
    volumes:
      - data-1:/data-1
  demo-2:
    container_name: demo-2
    image: redis:latest
    networks:
      - backend

networks:
  frontend:

  backend:


volumes:
  data-1:
